apiVersion: v2
name: homer
description: A dead simple static HOMepage for your servER to keep your services on hand, from a simple yaml configuration file.
home: https://github.com/gabe565/charts/tree/main/charts/homer
icon: https://raw.githubusercontent.com/bastienwirtz/homer/5418c6291a39d27aeee471673adba742080e1ccb/public/logo.png
type: application
version: 0.2.0
appVersion: v22.11.2
kubeVersion: ">=1.22.0-0"
keywords:
  - homer
  - dashboard
  - startpage
  - homepage
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
sources:
  - https://github.com/bastienwirtz/homer
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump common subchart to v1.2.1
