#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/linuxserver/bookstack
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: version-v23.08.3

# -- environment variables.
#    For more options see [BookStack .env.example](https://github.com/BookStackApp/BookStack/blob/release/.env.example.complete).
# @default -- See [values.yaml](./values.yaml)
env: {}

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local

persistence:
  # -- Configure persistence settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
   config:
     enabled: false
     retain: true
     # storageClass: ""
     # accessMode: ReadWriteOnce
     # size: 1Gi

# -- Enable and configure mariadb database subchart under this key.
#    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
# @default -- See [values.yaml](./values.yaml)
mariadb:
  enabled: false
  auth:
    database: bookstack
    username: bookstack
    password: changeme
    rootPassword: changeme
  primary:
    persistence:
      enabled: false
      # storageClass: ""
      # size: 8Gi

shelfPermissionsCron:
  # -- Enables a CronJob that copies shelf permissions to all child books.
  #    [[ref]](https://bookstackapp.com/docs/admin/commands/#copy-shelf-permission)
  enabled: false
  # -- Shelf permissions CronJob name
  nameOverride: copy-shelf-permissions
  controller:
    # @ignored
    type: cronjob
    cronjob:
      # -- Shelf permissions CronJob time
      schedule: 0 0 * * *
  # -- Shelf permissions CronJob command
  # @default -- See [values.yaml](./values.yaml)
  command:
    - php
    - /app/www/artisan
    - bookstack:copy-shelf-permissions
    - --no-interaction
    - --all

podSecurityContext:
  # -- Volume group permissions
  fsGroup: 911
