apiVersion: v2
name: plex
description: Plex organizes all of your personal media so you can enjoy it no matter where you are.
home: https://charts.gabe565.com/charts/plex/
icon: https://raw.githubusercontent.com/gabe565/charts/main/charts/plex/icon.svg
type: application
version: 0.0.1
# renovate datasource=docker depName=ghcr.io/linuxserver/plex
appVersion: version-1.31.3.6868-28fc46b27
kubeVersion: ">=1.22.0-0"
keywords:
  - media
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
sources:
  - https://plex.tv
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Add example media persistence values
    - kind: fixed
      description: Fix copy-paste error
  artifacthub.io/links: |-
    - name: App homepage
      url: https://plex.tv
    - name: Container Source
      url: https://github.com/linuxserver/docker-plex
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/plex
