apiVersion: v2
name: rss-bridge
description: The RSS feed for websites missing it.
home: https://charts.gabe565.com/charts/rss-bridge/
icon: https://raw.githubusercontent.com/RSS-Bridge/rss-bridge/987f42d6d44cc18e5c33441e742d15ffff6feb72/static/favicon.png
type: application
version: 0.3.6
# renovate datasource=docker depName=ghcr.io/rss-bridge/rss-bridge
appVersion: latest
kubeVersion: ">=1.22.0-0"
keywords:
  - rss-bridge
  - rss
  - feed
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.4.0
sources:
  - https://github.com/RSS-Bridge/rss-bridge
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update common Helm release to v1.4.0
    - kind: changed
      description: Update homepage URL
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/RSS-Bridge/rss-bridge
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/rss-bridge
