apiVersion: v2
name: rss-bridge
description: The RSS feed for websites missing it.
home: https://github.com/gabe565/charts/tree/main/charts/rss-bridge
icon: https://raw.githubusercontent.com/RSS-Bridge/rss-bridge/987f42d6d44cc18e5c33441e742d15ffff6feb72/static/favicon.png
type: application
version: 0.2.0
# renovate image=rssbridge/rss-bridge
appVersion: latest
kubeVersion: ">=1.22.0-0"
keywords:
  - rss-bridge
  - rss
  - feed
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
sources:
  - https://github.com/RSS-Bridge/rss-bridge
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump common subchart to v1.2.1
