apiVersion: v2
name: flame
description: Flame is self-hosted startpage for your server. Easily manage your apps and bookmarks with built-in editors.
home: https://charts.gabe565.com/charts/flame
icon: https://raw.githubusercontent.com/pawelmalak/flame/4ed29fe276b4282c67415f9788660df2a3a69b5c/client/public/icons/apple-touch-icon-180x180.png
type: application
version: 0.3.4
# renovate datasource=docker depName=pawelmalak/flame
appVersion: multiarch2.3.0
kubeVersion: ">=1.22.0-0"
keywords:
  - flame
  - dashboard
  - startpage
  - homepage
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
sources:
  - https://github.com/pawelmalak/flame
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Add Artifact Hub links annotation
    - kind: changed
      description: Update issue link
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/pawelmalak/flame
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/flame
