apiVersion: v2
name: flame
description: Flame is self-hosted startpage for your server. Easily manage your apps and bookmarks with built-in editors.
home: https://charts.gabe565.com/charts/flame/
icon: https://raw.githubusercontent.com/gabe565/charts/main/charts/flame/icon.svg
type: application
version: 0.5.3
# renovate datasource=docker depName=pawelmalak/flame
appVersion: multiarch2.3.1
kubeVersion: ">=1.22.0-0"
keywords:
  - flame
  - dashboard
  - startpage
  - homepage
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
sources:
  - https://github.com/pawelmalak/flame
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update common Helm release to v1.5.1
    - kind: added
      description: Add OCI install docs
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/pawelmalak/flame
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/flame
