apiVersion: v2
name: flame
description: Flame is self-hosted startpage for your server. Easily manage your apps and bookmarks with built-in editors.
home: https://github.com/gabe565/charts/tree/main/charts/flame
icon: https://raw.githubusercontent.com/pawelmalak/flame/4ed29fe276b4282c67415f9788660df2a3a69b5c/client/public/icons/apple-touch-icon-180x180.png
type: application
version: 0.2.0
appVersion: multiarch2.3.0
kubeVersion: ">=1.22.0-0"
keywords:
  - flame
  - dashboard
  - startpage
  - homepage
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
sources:
  - https://github.com/pawelmalak/flame
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump common subchart to v1.2.1
