apiVersion: v2
name: tandoor
description: Application for managing recipes, planning meals, building shopping lists and much much more!
home: https://charts.gabe565.com/charts/tandoor/
icon: https://raw.githubusercontent.com/vabene1111/recipes/master/docs/logo_color.svg
type: application
version: 0.9.9
# renovate datasource=docker depName=ghcr.io/tandoorrecipes/recipes
appVersion: 1.5.31
kubeVersion: ">=1.22.0-0"
keywords:
  - recipes
  - cookbook
  - cooking
  - meal-planner
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
  - name: postgresql
    version: 14.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/TandoorRecipes/recipes
annotations:
  artifacthub.io/alternativeName: tandoor-recipes
  artifacthub.io/changes: |-
    - kind: changed
      description: Update ghcr.io/tandoorrecipes/recipes docker tag to v1.5.31
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/TandoorRecipes/recipes
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/tandoor
