apiVersion: v2
name: tandoor
description: Application for managing recipes, planning meals, building shopping lists and much much more!
home: https://charts.gabe565.com/charts/tandoor
icon: https://raw.githubusercontent.com/vabene1111/recipes/master/docs/logo_color.svg
type: application
version: 0.5.0
# renovate datasource=docker depName=vabene1111/recipes
appVersion: 1.4.8
kubeVersion: ">=1.22.0-0"
keywords:
  - recipes
  - cookbook
  - cooking
  - meal-planner
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
  - name: postgresql
    version: 12.1.14
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/gabe565/charts/tree/main/charts/tandoor
  - https://docs.tandoor.dev/
  - https://github.com/TandoorRecipes/recipes
  - https://hub.docker.com/r/vabene1111/recipes
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Add example persistence values
    - kind: changed
      description: Comment out default ingress values
    - kind: changed
      description: Retain persistent volumes by default
