apiVersion: v2
name: tandoor
description: Application for managing recipes, planning meals, building shopping lists and much much more!
home: https://github.com/gabe565/charts/tree/main/charts/tandoor
icon: https://raw.githubusercontent.com/vabene1111/recipes/master/docs/logo_color.svg
type: application
version: 0.2.0
# renovate image=vabene1111/recipes
appVersion: 1.4.5
kubeVersion: ">=1.22.0-0"
keywords:
  - recipes
  - cookbook
  - cooking
  - meal-planner
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://docs.tandoor.dev/
  - https://github.com/TandoorRecipes/recipes
  - https://hub.docker.com/r/vabene1111/recipes
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump common subchart to v1.2.1
    - kind: changed
      description: Bump postgresql subchart to v11.9.13
