apiVersion: v2
name: scanservjs
description: scanservjs is a web UI frontend for your scanner. It allows you to share one or more scanners (using SANE) on a network without the need for drivers or complicated installation.
home: https://charts.gabe565.com/charts/scanservjs
type: application
version: 0.4.3
# renovate datasource=docker depName=sbs20/scanservjs
appVersion: release-v2.25.2
kubeVersion: ">=1.22.0-0"
keywords:
  - scanservjs
  - scanner
  - sane
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.1
sources:
  - https://github.com/gabe565/charts/tree/main/charts/scanservjs
  - https://github.com/sbs20/scanservjs
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update sbs20/scanservjs Docker tag to release-v2.25.2
