apiVersion: v2
name: pictshare
description: PictShare is an open source image, mp4, pastebin hosting service with a simple resizing and upload API that you can host yourself.
home: https://charts.gabe565.com/charts/pictshare/
icon: https://camo.githubusercontent.com/6efdab1c63d518fafc5e735001c5ed45e7cbd4958952cdd972e2630eee881d97/68747470733a2f2f7069637473686172652e6e65742f706868796e6a2e706e67
type: application
version: 0.4.3
# renovate datasource=docker depName=ghcr.io/hascheksolutions/pictshare
appVersion: 74ccf9f6
kubeVersion: ">=1.22.0-0"
keywords:
  - pictshare
  - image
  - picture
  - image-uploader
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.4.0
sources:
  - https://github.com/HaschekSolutions/pictshare
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update common Helm release to v1.4.0
    - kind: changed
      description: Update homepage URL
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/HaschekSolutions/pictshare
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/pictshare
