apiVersion: v2
name: qbittorrent
description: The qBittorrent project aims to provide an open-source software alternative to ÂµTorrent.
home: https://charts.gabe565.com/charts/qbittorrent
icon: https://raw.githubusercontent.com/qbittorrent/qBittorrent/master/src/icons/qbittorrent-tray.svg
type: application
version: 0.0.4
# renovate datasource=docker depName=ghcr.io/linuxserver/qbittorrent
appVersion: version-4.5.2-r0
kubeVersion: ">=1.22.0-0"
keywords:
  - torrent
  - bittorrent
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
sources:
  - https://github.com/qbittorrent/qBittorrent
  - https://github.com/linuxserver/docker-qbittorrent
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Add Artifact Hub links annotation
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/qbittorrent/qBittorrent
    - name: Container Source
      url: https://github.com/linuxserver/docker-qbittorrent
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/qbittorrent
