#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/linuxserver/qbittorrent
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: version-4.5.5-r0

# -- environment variables. [[ref]](https://github.com/linuxserver/docker-qbittorrent#parameters)
# @default -- See [values.yaml](./values.yaml)
env:
  # -- Set the container timezone
  TZ: UTC

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    ports:
      http:
        port: 8080
  bittorrent:
    enabled: false
    ports:
      bittorrent:
        enabled: true
        port: 6881
        protocol: TCP

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local

# -- Configure persistence settings for the chart under this key.
# Set `enabled` to `true' to create persistant volumes for each of these.
# @default -- See values.yaml
persistence:
  # Configuration files
  config:
    enabled: false
    # retain: true
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 1Gi

  # Optional - Download location - Allows dedicated volume for storage of downloaded files.
  downloads:
    enabled: false
    # mountPath: /downloads
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 10Gi

  # Optional - Allows linking to an existing media library scraping location.
  media:
    enabled: false
    # mountPath: /media
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 10Gi
