apiVersion: v2
name: domain-watch
description: Tool to watch whois reports and notify when statuses change or expiration is incoming.
home: https://github.com/gabe565/charts/tree/main/charts/domain-watch
type: application
version: 0.2.0
appVersion: latest
kubeVersion: ">=1.22.0-0"
keywords:
  - domain
  - whois
  - alert
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
sources:
  - https://github.com/gabe565/domain-watch
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump common subchart to v1.2.1
