apiVersion: v2
name: domain-watch
description: Tool to watch whois reports and notify when statuses change or expiration is incoming.
home: https://charts.gabe565.com/charts/domain-watch
type: application
version: 0.2.1
# renovate image=ghcr.io/gabe565/domain-watch
appVersion: latest
kubeVersion: ">=1.22.0-0"
keywords:
  - domain
  - whois
  - alert
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
sources:
  - https://github.com/gabe565/charts/tree/main/charts/domain-watch
  - https://github.com/gabe565/domain-watch
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update homepage to charts.gabe565.com and add to readme
    - kind: added
      description: Add GitHub repo to sources
