apiVersion: v2
name: changedetection-io
description: Live your data-life pro-actively, track website content changes and receive notifications via Discord, Email, Slack, Telegram and 70+ more.
home: https://charts.gabe565.com/charts/changedetection-io
icon: https://raw.githubusercontent.com/gabe565/charts/main/charts/changedetection-io/icon.png
type: application
version: 0.5.3
# renovate datasource=docker depName=ghcr.io/dgtlmoon/changedetection.io
appVersion: 0.41
kubeVersion: ">=1.22.0-0"
keywords:
  - changedetection.io
  - change-detection
  - website-monitoring
  - website-change-tracker
sources:
  - https://github.com/dgtlmoon/changedetection.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Add Artifact Hub links annotation
    - kind: changed
      description: Update issue link
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/dgtlmoon/changedetection.io
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/changedetection-io
