apiVersion: v2
name: matrimony
description: Self-hosted wedding site configured via YAML
home: https://charts.gabe565.com/charts/matrimony
icon: https://raw.githubusercontent.com/gabe565/matrimony/b13163b384b27273080deb8d57d1222ba11337f9/frontend/public/img/logo.svg
type: application
version: 0.4.1
# renovate datasource=docker depName=ghcr.io/gabe565/matrimony
appVersion: latest
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
sources:
  - https://github.com/gabe565/matrimony
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Clean up chart sources
