apiVersion: v2
name: matrimony
description: Self-hosted wedding site configured via YAML
home: https://github.com/gabe565/charts/tree/main/charts/matrimony
type: application
version: 0.2.0
appVersion: latest
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
sources:
  - https://github.com/gabe565/matrimony
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump common subchart to v1.2.1
