apiVersion: v2
name: monica
description: Personal CRM. Remember everything about your friends, family and business relationships.
home: https://charts.gabe565.com/charts/monica
icon: https://raw.githubusercontent.com/monicahq/monica/main/public/img/monica.svg
type: application
version: 0.5.0
# renovate datasource=docker depName=monica
appVersion: 4.0.0-fpm-alpine
kubeVersion: ">=1.22.0-0"
keywords:
  - crm
sources:
  - https://github.com/gabe565/charts/tree/main/charts/monica
  - https://github.com/monicahq/monica
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
  - name: mariadb
    version: 11.4.6
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Add example ingress values
