apiVersion: v2
name: ascii-telnet
description: Star Wars telnet server
home: https://github.com/gabe565/charts/tree/main/charts/ascii-telnet
type: application
version: 0.2.0
# renovate image=ghcr.io/gabe565/ascii-telnet-go
appVersion: latest
kubeVersion: ">=1.22.0-0"
keywords:
  - ascii-art
  - star-wars
  - telnet
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
sources:
  - https://github.com/gabe565/ascii-telnet-go
  - https://github.com/gabe565/ascii-telnet-rust
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump common subchart to v1.2.1
