apiVersion: v2
name: ascii-telnet
description: Star Wars telnet server
home: https://charts.gabe565.com/charts/ascii-telnet
icon: https://raw.githubusercontent.com/gabe565/ascii-telnet-go/a1fd5c9df2fb3a177949c9511b62407c83aedefe/assets/icon.svg
type: application
version: 0.3.4
# renovate datasource=docker depName=ghcr.io/gabe565/ascii-telnet-go
appVersion: latest
kubeVersion: ">=1.22.0-0"
keywords:
  - ascii-art
  - star-wars
  - telnet
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
sources:
  - https://github.com/gabe565/ascii-telnet-go
  - https://github.com/gabe565/ascii-telnet-rust
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Add Artifact Hub links annotation
    - kind: changed
      description: Update issue link
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/gabe565/ascii-telnet-go
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/ascii-telnet
