#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository.
  #    Defaults to Go implementation at [`ghcr.io/gabe565/ascii-telnet-go`](https://ghcr.io/gabe565/ascii-telnet-go),
  #    but can also be set to [`ghcr.io/gabe565/ascii-telnet-rust`](https://ghcr.io/gabe565/ascii-telnet-rust).
  repository: ghcr.io/gabe565/ascii-telnet-go
  # -- image pull policy
  pullPolicy: Always
  # -- image tag
  tag: ""

controller:
  # -- Set the controller upgrade strategy
  strategy: RollingUpdate

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
      http:
        enabled: false
        primary: false
      telnet:
        enabled: true
        primary: true
        protocol: TCP
        port: 23
