apiVersion: v2
name: limo
description: A file upload server.
home: https://charts.gabe565.com/charts/limo
type: application
version: 0.2.0
# renovate image=ghcr.io/gabe565/limo
appVersion: latest
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/gabe565/limo
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update homepage to charts.gabe565.com and add to readme
