apiVersion: v2
name: limo
description: A file upload server.
home: https://charts.gabe565.com/charts/limo
type: application
version: 0.5.2
# renovate datasource=docker depName=ghcr.io/gabe565/limo
appVersion: latest
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
  - name: postgresql
    version: 12.1.14
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/gabe565/limo
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Add Artifact Hub links annotation
    - kind: changed
      description: Update issue link
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/gabe565/limo
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/limo
