apiVersion: v2
name: memos
description: A lightweight, self-hosted memo hub. Open Source and Free forever.
home: https://charts.gabe565.com/charts/memos/
icon: https://raw.githubusercontent.com/gabe565/charts/main/charts/memos/icon.png
type: application
version: 0.5.2
# renovate datasource=docker depName=ghcr.io/usememos/memos
appVersion: 0.13.1
kubeVersion: ">=1.22.0-0"
keywords:
  - memo
  - markdown
  - note-taking
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
sources:
  - https://github.com/usememos/memos
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: Set `MEMOS_PORT` to fix startup failures
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/usememos/memos
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/memos
