#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: headscale/headscale
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: ""

# -- Environment variables. [[ref]](https://github.com/juanfont/headscale/blob/main/config-example.yaml)
# @default -- See values.yaml
env:
  # -- Defines the base domain to create the hostnames for MagicDNS.
  # `base_domain` must be a FQDNs, without the trailing dot.
  # The FQDN of the hosts will be
  # `hostname.namespace.base_domain` (e.g., _myhost.mynamespace.example.com_).
  HEADSCALE_DNS_CONFIG_BASE_DOMAIN: example.com

# -- Secret environment variables.
# @default -- See values.yaml
secret: {}
  # HEADSCALE_OIDC_ISSUER: ""
  # HEADSCALE_OIDC_CLIENT_ID: ""
  # HEADSCALE_OIDC_CLIENT_SECRET: ""

service:
  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  main:
    ports:
      http:
        port: 8080
      metrics:
        enabled: true
        port: 9090
      grpc:
        port: 50443

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

persistence:
  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  config:
    enabled: false
    mountPath: /etc/headscale

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  enabled: false
  auth:
    database: headscale
    username: headscale
    password: headscale-pass
  primary:
    persistence:
      enabled: true
