apiVersion: v2
name: nightscout
description: Web-based CGM (Continuous Glucose Monitor) to allow multiple caregivers to remotely view a patient's glucose data in real time.
home: https://charts.gabe565.com/charts/nightscout
icon: https://raw.githubusercontent.com/nightscout/cgm-remote-monitor/71c2363b7be387cda899669be2bfd6ddbfe70198/static/images/large.png
type: application
version: 0.4.0
# renovate image=nightscout/cgm-remote-monitor
appVersion: 14.2.6
kubeVersion: ">=1.22.0-0"
keywords:
  - nightscout
  - cgm
  - blood-sugar
  - diabetes
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
  - name: mongodb
    version: 13.6.2
    repository: https://charts.bitnami.com/bitnami
sources:
  - https://github.com/nightscout/cgm-remote-monitor
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update homepage to charts.gabe565.com and add to readme
