apiVersion: v2
name: hammond
description: A self-hosted vehicle expense tracking system with support for multiple users.
home: https://charts.gabe565.com/charts/hammond/
icon: https://raw.githubusercontent.com/akhilrex/hammond/84cba2c7f26f6d3f81c49b132110b24ac97c7b49/ui/public/touch-icon.png
type: application
version: 0.4.0
# renovate datasource=docker depName=akhilrex/hammond
appVersion: 1.0.0
kubeVersion: ">=1.22.0-0"
keywords:
  - hammond
  - vehicle
  - expense-tracker
  - clarkson
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.4.0
sources:
  - https://github.com/akhilrex/hammond
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update common Helm release to v1.4.0
    - kind: changed
      description: Update homepage URL
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/akhilrex/hammond
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/hammond
