apiVersion: v2
name: relax-sounds
description: Relax Sounds is a website that lets you stream relaxing sounds to your browser or over Google Cast.
home: https://github.com/gabe565/charts/tree/main/charts/relax-sounds
icon: https://raw.githubusercontent.com/gabe565/relax-sounds/93681cad1585cd14203a39c6b3c5de525f30619e/frontend/public/img/icons/android-chrome-512x512.png
type: application
version: 0.2.0
# renovate image=ghcr.io/gabe565/relax-sounds
appVersion: latest
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
sources:
  - https://github.com/gabe565/relax-sounds
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump common subchart to v1.2.1
