apiVersion: v2
name: vaultwarden
description: Unofficial Bitwarden compatible server written in Rust.
home: https://github.com/gabe565/charts/tree/main/charts/vaultwarden
icon: https://raw.githubusercontent.com/dani-garcia/vaultwarden/7cb19ef767142b773ab44a457940844589432a74/src/static/images/vaultwarden-icon.png
type: application
version: 0.2.0
appVersion: 1.27.0-alpine
kubeVersion: ">=1.22.0-0"
keywords:
  - vaultwarden
  - bitwarden
  - bitwarden_rs
sources:
  - https://github.com/dani-garcia/vaultwarden
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
  - name: mariadb
    version: 11.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump common subchart to v1.2.1
    - kind: changed
      description: Bump mariadb subchart to v11.4.2
    - kind: changed
      description: Bump postgresql subchart to v11.9.13
