apiVersion: v2
name: vaultwarden
description: Unofficial Bitwarden compatible server written in Rust.
home: https://charts.gabe565.com/charts/vaultwarden/
icon: https://raw.githubusercontent.com/dani-garcia/vaultwarden/d57b69952db6eb12987a9668fea6b72df79cfa41/resources/vaultwarden-icon.svg
type: application
version: 0.10.0
# renovate datasource=docker depName=ghcr.io/dani-garcia/vaultwarden
appVersion: 1.29.1-alpine
kubeVersion: ">=1.22.0-0"
keywords:
  - vaultwarden
  - bitwarden
  - bitwarden_rs
sources:
  - https://github.com/dani-garcia/vaultwarden
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
  - name: mariadb
    version: 11.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 12.2.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: BREAKING - Change default port from 80 to 8080
    - kind: removed
      description: BREAKING - Remove dedicated WebSocket port
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/dani-garcia/vaultwarden
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/vaultwarden
