apiVersion: v2
name: podgrab
description: A self-hosted podcast manager to download episodes as soon as they become live.
home: https://charts.gabe565.com/charts/podgrab/
type: application
version: 0.5.2
# renovate datasource=docker depName=ghcr.io/akhilrex/podgrab
appVersion: 1.0.0
kubeVersion: ">=1.22.0-0"
keywords:
  - podgrab
  - podcast
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
sources:
  - https://github.com/akhilrex/podgrab
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Pin bjw-s common chart links to v1
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/akhilrex/podgrab
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/podgrab
