apiVersion: v2
name: podgrab
description: A self-hosted podcast manager to download episodes as soon as they become live.
home: https://charts.gabe565.com/charts/podgrab
type: application
version: 0.2.1
# renovate image=ghcr.io/akhilrex/podgrab
appVersion: 1.0.0
kubeVersion: ">=1.22.0-0"
keywords:
  - podgrab
  - podcast
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
sources:
  - https://github.com/gabe565/charts/tree/main/charts/podgrab
  - https://github.com/akhilrex/podgrab
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update homepage to charts.gabe565.com and add to readme
    - kind: added
      description: Add GitHub repo to sources
