version: "3.9"

services:
  jekyll:
    image: jekyll/jekyll:3
    command: [jekyll, serve]
    environment:
      PAGES_REPO_NWO: gabe565/charts
    platform: linux/amd64
    restart: on-failure
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - .:/srv/jekyll
      - cache:/usr/local/bundle

volumes:
  cache: {}
