apiVersion: v2
name: generic-device-plugin
description: The generic-device-plugin enables allocating generic Linux devices, such as serial devices, the FUSE device, or video cameras, to Kubernetes Pods
home: https://charts.gabe565.com/charts/generic-device-plugin/
type: application
version: 0.1.2
# renovate datasource=docker depName=ghcr.io/squat/generic-device-plugin
appVersion: latest
kubeVersion: ">=1.22.0-0"
keywords:
  - device-plugin
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
sources:
  - https://github.com/squat/generic-device-plugin
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update common Helm release to v1.5.1
    - kind: added
      description: Add OCI install docs
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/squat/generic-device-plugin
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/generic-device-plugin
