apiVersion: v2
name: transsmute
description: Transsmute builds RSS feeds for websites that don't provide them.
home: https://charts.gabe565.com/charts/transsmute/
icon: https://raw.githubusercontent.com/gabe565/transsmute/ce624f8c903654ead37489d8d274b97d526d397a/assets/icon.svg
type: application
version: 0.3.6
# renovate datasource=docker depName=ghcr.io/gabe565/transsmute
appVersion: latest
kubeVersion: ">=1.22.0-0"
keywords:
  - transsmute
  - rss
  - feed
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.4.0
sources:
  - https://github.com/gabe565/transsmute
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update common Helm release to v1.4.0
    - kind: changed
      description: Update homepage URL
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/gabe565/transsmute
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/transsmute
