apiVersion: v2
name: transsmute
description: Transsmute builds RSS feeds for websites that don't provide them.
home: https://github.com/gabe565/charts/tree/main/charts/transsmute
type: application
version: 0.2.0
# renovate image=ghcr.io/gabe565/transsmute
appVersion: latest
kubeVersion: ">=1.22.0-0"
keywords:
  - transsmute
  - rss
  - feed
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1
sources:
  - https://github.com/gabe565/transsmute
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump common subchart to v1.2.1
