apiVersion: v2
name: miniflux
description: Miniflux is a minimalist and opinionated feed reader.
home: https://charts.gabe565.com/charts/miniflux/
icon: https://raw.githubusercontent.com/miniflux/logo/40cb83cc5b190212ad29fb4d5db6b52b335e4dc2/icon.svg
type: application
version: 0.4.8
# renovate datasource=docker depName=ghcr.io/miniflux/miniflux
appVersion: 2.0.43
kubeVersion: ">=1.22.0-0"
keywords:
  - miniflux
  - rss
  - news
  - feed
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.4.0
  - name: postgresql
    version: 12.2.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/miniflux/v2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update postgresql Helm release to v12.2.7
    - kind: changed
      description: Update common Helm release to v1.4.0
    - kind: changed
      description: Update homepage URL
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/miniflux/v2
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/miniflux
