apiVersion: v2
name: ascii-movie
description: Star Wars movie SSH and Telnet server
home: https://charts.gabe565.com/charts/ascii-movie/
icon: https://raw.githubusercontent.com/gabe565/ascii-movie/a1fd5c9df2fb3a177949c9511b62407c83aedefe/assets/icon.svg
type: application
version: 0.12.1
# renovate datasource=docker depName=ghcr.io/gabe565/ascii-movie
appVersion: 1.6.0
kubeVersion: ">=1.22.0-0"
keywords:
  - ascii-art
  - star-wars
  - telnet
  - ssh
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
sources:
  - https://github.com/gabe565/ascii-movie
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Pin bjw-s common chart links to v1
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/gabe565/ascii-movie
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/ascii-movie
