apiVersion: v2
name: mnemonic-ninja
description: Mnemonic Ninja is a website to convert between a number and its corresponding word to aid in memorization.
home: https://charts.gabe565.com/charts/mnemonic-ninja
icon: https://raw.githubusercontent.com/gabe565/mnemonic-ninja/20b5c559fb0147c5f3c0c1cc5a3841d371259b78/frontend/src/assets/logo.svg
type: application
version: 0.3.1
# renovate image=ghcr.io/gabe565/mnemonic-ninja
appVersion: latest
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.0
sources:
  - https://github.com/gabe565/charts/tree/main/charts/mnemonic-ninja
  - https://github.com/gabe565/mnemonic-ninja
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Tweak env default to link to values.yaml
