apiVersion: v2
name: mnemonic-ninja
description: Mnemonic Ninja is a website to convert between a number and its corresponding word to aid in memorization.
home: https://charts.gabe565.com/charts/mnemonic-ninja/
icon: https://raw.githubusercontent.com/gabe565/mnemonic-ninja/465602c/src/assets/logo.svg
type: application
version: 0.5.2
# renovate datasource=docker depName=ghcr.io/gabe565/mnemonic-ninja
appVersion: latest
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
sources:
  - https://github.com/gabe565/mnemonic-ninja
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Pin bjw-s common chart links to v1
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/gabe565/mnemonic-ninja
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/mnemonic-ninja
