apiVersion: v2
name: smarter-device-manager
description: Manage hardware resource allocation without a need for privileged containers.
home: https://charts.gabe565.com/charts/smarter-device-manager/
icon: https://gitlab.com/uploads/-/system/group/avatar/6339043/ARM1636_Project_Logo_ST2_RGB_V1.png
type: application
version: 0.5.1
# renovate datasource=docker depName=registry.gitlab.com/arm-research/smarter/smarter-device-manager
appVersion: v1.20.11
kubeVersion: ">=1.22.0-0"
keywords:
  - kubernetes
  - cluster
  - hardware
  - device
  - usb
sources:
  - https://gitlab.com/arm-research/smarter/smarter-device-manager
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update common Helm release to v1.5.1
    - kind: added
      description: Add OCI install docs
  artifacthub.io/links: |-
    - name: App Source
      url: https://gitlab.com/arm-research/smarter/smarter-device-manager
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/smarter-device-manager
